<?xml version="1.0" encoding="utf-8"?><Database Name="Risk" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=JVALLEJO-PC\sql2008;Initial Catalog=Risk;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RiskConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tRiesgos" Member="tRiesgos">
    <Type Name="tRiesgo">
      <Column Name="IdRiesgo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodRiesgoGenerico" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodRiesgo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodRiesgoLocalizado" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdClasificacion1" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="IdClasificacion2" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="IdClasificacion3" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ejemplo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Justificacion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IdSegmentacion1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdResponsable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdControlesOportunidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdControlesEfectividad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vigencia" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="tRiesgo_tRiesgos_ControlOportunidad" Member="tRiesgos_ControlOportunidads" ThisKey="IdControlesOportunidad" OtherKey="IdControlOportunidad" Type="tRiesgos_ControlOportunidad" />
      <Association Name="tRiesgo_tRiesgos_Clasificaciones1" Member="tRiesgos_Clasificaciones1s" ThisKey="IdClasificacion1" OtherKey="IdEstructura" Type="tRiesgos_Clasificaciones1" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_ControlOportunidad" Member="tRiesgos_ControlOportunidads">
    <Type Name="tRiesgos_ControlOportunidad">
      <Column Name="IdControlOportunidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Oportunidad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tRiesgo_tRiesgos_ControlOportunidad" Member="tRiesgo" ThisKey="IdControlOportunidad" OtherKey="IdControlesOportunidad" Type="tRiesgo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_Clasificaciones" Member="tRiesgos_Clasificaciones1s">
    <Type Name="tRiesgos_Clasificaciones1">
      <Column Name="IdEstructura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodNivel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodCompleto" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="tRiesgo_tRiesgos_Clasificaciones1" Member="tRiesgo" ThisKey="IdEstructura" OtherKey="IdClasificacion1" Type="tRiesgo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_Clasificaciones" Member="tRiesgos_Clasificaciones2s">
    <Type Name="tRiesgos_Clasificaciones2">
      <Column Name="IdEstructura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodNivel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodCompleto" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_Clasificaciones" Member="tRiesgos_Clasificaciones3s">
    <Type Name="tRiesgos_Clasificaciones3">
      <Column Name="IdEstructura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodNivel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodCompleto" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
</Database>