#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Risk")]
	public partial class Riesgos_BDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttRiesgo(tRiesgo instance);
    partial void UpdatetRiesgo(tRiesgo instance);
    partial void DeletetRiesgo(tRiesgo instance);
    partial void InserttRiesgos_Categoria(tRiesgos_Categoria instance);
    partial void UpdatetRiesgos_Categoria(tRiesgos_Categoria instance);
    partial void DeletetRiesgos_Categoria(tRiesgos_Categoria instance);
    partial void InserttRiesgos_Clasificaciones(tRiesgos_Clasificaciones instance);
    partial void UpdatetRiesgos_Clasificaciones(tRiesgos_Clasificaciones instance);
    partial void DeletetRiesgos_Clasificaciones(tRiesgos_Clasificaciones instance);
    partial void InserttRiesgosEvaluaciones(tRiesgosEvaluaciones instance);
    partial void UpdatetRiesgosEvaluaciones(tRiesgosEvaluaciones instance);
    partial void DeletetRiesgosEvaluaciones(tRiesgosEvaluaciones instance);
    partial void InserttEva_Frecuencia(tEva_Frecuencia instance);
    partial void UpdatetEva_Frecuencia(tEva_Frecuencia instance);
    partial void DeletetEva_Frecuencia(tEva_Frecuencia instance);
    partial void InserttEva_Severidad(tEva_Severidad instance);
    partial void UpdatetEva_Severidad(tEva_Severidad instance);
    partial void DeletetEva_Severidad(tEva_Severidad instance);
    #endregion
		
		public Riesgos_BDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RiskConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Riesgos_BDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Riesgos_BDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Riesgos_BDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Riesgos_BDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tRiesgo> tRiesgos
		{
			get
			{
				return this.GetTable<tRiesgo>();
			}
		}
		
		public System.Data.Linq.Table<tRiesgos_Categoria> tRiesgos_Categorias
		{
			get
			{
				return this.GetTable<tRiesgos_Categoria>();
			}
		}
		
		public System.Data.Linq.Table<tRiesgos_Clasificaciones> tRiesgos_Clasificaciones
		{
			get
			{
				return this.GetTable<tRiesgos_Clasificaciones>();
			}
		}
		
		public System.Data.Linq.Table<qRiesgosNombre> qRiesgosNombres
		{
			get
			{
				return this.GetTable<qRiesgosNombre>();
			}
		}
		
		public System.Data.Linq.Table<tRiesgosEvaluaciones> tRiesgosEvaluaciones
		{
			get
			{
				return this.GetTable<tRiesgosEvaluaciones>();
			}
		}
		
		public System.Data.Linq.Table<tEva_Frecuencia> tEva_Frecuencia
		{
			get
			{
				return this.GetTable<tEva_Frecuencia>();
			}
		}
		
		public System.Data.Linq.Table<tEva_Severidad> tEva_Severidad
		{
			get
			{
				return this.GetTable<tEva_Severidad>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tRiesgos")]
	public partial class tRiesgo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRiesgo;
		
		private string _CodRiesgoGenerico;
		
		private string _CodRiesgo;
		
		private string _CodRiesgoLocalizado;
		
		private string _Nombre;
		
		private System.Nullable<int> _IdCategoria;
		
		private System.Nullable<int> _IdClasificacion1;
		
		private System.Nullable<int> _IdClasificacion2;
		
		private System.Nullable<int> _IdClasificacion3;
		
		private string _Descripcion;
		
		private string _Ejemplo;
		
		private string _Justificacion;
		
		private System.Nullable<int> _IdSegmentacion1;
		
		private System.Nullable<int> _IdResponsable;
		
		private System.Nullable<int> _IdSupervisor;
		
		private System.Nullable<int> _IdControlesOportunidad;
		
		private System.Nullable<int> _IdControlesEfectividad;
		
		private string _Vigencia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRiesgoChanging(int value);
    partial void OnIdRiesgoChanged();
    partial void OnCodRiesgoGenericoChanging(string value);
    partial void OnCodRiesgoGenericoChanged();
    partial void OnCodRiesgoChanging(string value);
    partial void OnCodRiesgoChanged();
    partial void OnCodRiesgoLocalizadoChanging(string value);
    partial void OnCodRiesgoLocalizadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdCategoriaChanging(System.Nullable<int> value);
    partial void OnIdCategoriaChanged();
    partial void OnIdClasificacion1Changing(System.Nullable<int> value);
    partial void OnIdClasificacion1Changed();
    partial void OnIdClasificacion2Changing(System.Nullable<int> value);
    partial void OnIdClasificacion2Changed();
    partial void OnIdClasificacion3Changing(System.Nullable<int> value);
    partial void OnIdClasificacion3Changed();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnEjemploChanging(string value);
    partial void OnEjemploChanged();
    partial void OnJustificacionChanging(string value);
    partial void OnJustificacionChanged();
    partial void OnIdSegmentacion1Changing(System.Nullable<int> value);
    partial void OnIdSegmentacion1Changed();
    partial void OnIdResponsableChanging(System.Nullable<int> value);
    partial void OnIdResponsableChanged();
    partial void OnIdSupervisorChanging(System.Nullable<int> value);
    partial void OnIdSupervisorChanged();
    partial void OnIdControlesOportunidadChanging(System.Nullable<int> value);
    partial void OnIdControlesOportunidadChanged();
    partial void OnIdControlesEfectividadChanging(System.Nullable<int> value);
    partial void OnIdControlesEfectividadChanged();
    partial void OnVigenciaChanging(string value);
    partial void OnVigenciaChanged();
    #endregion
		
		public tRiesgo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRiesgo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRiesgo
		{
			get
			{
				return this._IdRiesgo;
			}
			set
			{
				if ((this._IdRiesgo != value))
				{
					this.OnIdRiesgoChanging(value);
					this.SendPropertyChanging();
					this._IdRiesgo = value;
					this.SendPropertyChanged("IdRiesgo");
					this.OnIdRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRiesgoGenerico", DbType="NVarChar(50)")]
		public string CodRiesgoGenerico
		{
			get
			{
				return this._CodRiesgoGenerico;
			}
			set
			{
				if ((this._CodRiesgoGenerico != value))
				{
					this.OnCodRiesgoGenericoChanging(value);
					this.SendPropertyChanging();
					this._CodRiesgoGenerico = value;
					this.SendPropertyChanged("CodRiesgoGenerico");
					this.OnCodRiesgoGenericoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRiesgo", DbType="NVarChar(50)")]
		public string CodRiesgo
		{
			get
			{
				return this._CodRiesgo;
			}
			set
			{
				if ((this._CodRiesgo != value))
				{
					this.OnCodRiesgoChanging(value);
					this.SendPropertyChanging();
					this._CodRiesgo = value;
					this.SendPropertyChanged("CodRiesgo");
					this.OnCodRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRiesgoLocalizado", DbType="NVarChar(250)")]
		public string CodRiesgoLocalizado
		{
			get
			{
				return this._CodRiesgoLocalizado;
			}
			set
			{
				if ((this._CodRiesgoLocalizado != value))
				{
					this.OnCodRiesgoLocalizadoChanging(value);
					this.SendPropertyChanging();
					this._CodRiesgoLocalizado = value;
					this.SendPropertyChanged("CodRiesgoLocalizado");
					this.OnCodRiesgoLocalizadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int")]
		public System.Nullable<int> IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClasificacion1", DbType="Int")]
		public System.Nullable<int> IdClasificacion1
		{
			get
			{
				return this._IdClasificacion1;
			}
			set
			{
				if ((this._IdClasificacion1 != value))
				{
					this.OnIdClasificacion1Changing(value);
					this.SendPropertyChanging();
					this._IdClasificacion1 = value;
					this.SendPropertyChanged("IdClasificacion1");
					this.OnIdClasificacion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClasificacion2", DbType="Int")]
		public System.Nullable<int> IdClasificacion2
		{
			get
			{
				return this._IdClasificacion2;
			}
			set
			{
				if ((this._IdClasificacion2 != value))
				{
					this.OnIdClasificacion2Changing(value);
					this.SendPropertyChanging();
					this._IdClasificacion2 = value;
					this.SendPropertyChanged("IdClasificacion2");
					this.OnIdClasificacion2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClasificacion3", DbType="Int")]
		public System.Nullable<int> IdClasificacion3
		{
			get
			{
				return this._IdClasificacion3;
			}
			set
			{
				if ((this._IdClasificacion3 != value))
				{
					this.OnIdClasificacion3Changing(value);
					this.SendPropertyChanging();
					this._IdClasificacion3 = value;
					this.SendPropertyChanged("IdClasificacion3");
					this.OnIdClasificacion3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ejemplo", DbType="NVarChar(250)")]
		public string Ejemplo
		{
			get
			{
				return this._Ejemplo;
			}
			set
			{
				if ((this._Ejemplo != value))
				{
					this.OnEjemploChanging(value);
					this.SendPropertyChanging();
					this._Ejemplo = value;
					this.SendPropertyChanged("Ejemplo");
					this.OnEjemploChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Justificacion", DbType="NVarChar(MAX)")]
		public string Justificacion
		{
			get
			{
				return this._Justificacion;
			}
			set
			{
				if ((this._Justificacion != value))
				{
					this.OnJustificacionChanging(value);
					this.SendPropertyChanging();
					this._Justificacion = value;
					this.SendPropertyChanged("Justificacion");
					this.OnJustificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSegmentacion1", DbType="Int")]
		public System.Nullable<int> IdSegmentacion1
		{
			get
			{
				return this._IdSegmentacion1;
			}
			set
			{
				if ((this._IdSegmentacion1 != value))
				{
					this.OnIdSegmentacion1Changing(value);
					this.SendPropertyChanging();
					this._IdSegmentacion1 = value;
					this.SendPropertyChanged("IdSegmentacion1");
					this.OnIdSegmentacion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResponsable", DbType="Int")]
		public System.Nullable<int> IdResponsable
		{
			get
			{
				return this._IdResponsable;
			}
			set
			{
				if ((this._IdResponsable != value))
				{
					this.OnIdResponsableChanging(value);
					this.SendPropertyChanging();
					this._IdResponsable = value;
					this.SendPropertyChanged("IdResponsable");
					this.OnIdResponsableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSupervisor", DbType="Int")]
		public System.Nullable<int> IdSupervisor
		{
			get
			{
				return this._IdSupervisor;
			}
			set
			{
				if ((this._IdSupervisor != value))
				{
					this.OnIdSupervisorChanging(value);
					this.SendPropertyChanging();
					this._IdSupervisor = value;
					this.SendPropertyChanged("IdSupervisor");
					this.OnIdSupervisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdControlesOportunidad", DbType="Int")]
		public System.Nullable<int> IdControlesOportunidad
		{
			get
			{
				return this._IdControlesOportunidad;
			}
			set
			{
				if ((this._IdControlesOportunidad != value))
				{
					this.OnIdControlesOportunidadChanging(value);
					this.SendPropertyChanging();
					this._IdControlesOportunidad = value;
					this.SendPropertyChanged("IdControlesOportunidad");
					this.OnIdControlesOportunidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdControlesEfectividad", DbType="Int")]
		public System.Nullable<int> IdControlesEfectividad
		{
			get
			{
				return this._IdControlesEfectividad;
			}
			set
			{
				if ((this._IdControlesEfectividad != value))
				{
					this.OnIdControlesEfectividadChanging(value);
					this.SendPropertyChanging();
					this._IdControlesEfectividad = value;
					this.SendPropertyChanged("IdControlesEfectividad");
					this.OnIdControlesEfectividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vigencia", DbType="NVarChar(20)")]
		public string Vigencia
		{
			get
			{
				return this._Vigencia;
			}
			set
			{
				if ((this._Vigencia != value))
				{
					this.OnVigenciaChanging(value);
					this.SendPropertyChanging();
					this._Vigencia = value;
					this.SendPropertyChanged("Vigencia");
					this.OnVigenciaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tRiesgos_Categorias")]
	public partial class tRiesgos_Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCategoria;
		
		private string _Categoria;
		
		private System.Nullable<int> _Orden;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCategoriaChanging(int value);
    partial void OnIdCategoriaChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnOrdenChanging(System.Nullable<int> value);
    partial void OnOrdenChanged();
    #endregion
		
		public tRiesgos_Categoria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NVarChar(50)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int")]
		public System.Nullable<int> Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tRiesgos_Clasificaciones")]
	public partial class tRiesgos_Clasificaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstructura;
		
		private string _CodNivel;
		
		private string _Nombre;
		
		private System.Nullable<int> _Nivel;
		
		private System.Nullable<int> _idPadre;
		
		private System.Nullable<int> _Orden;
		
		private string _CodCompleto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstructuraChanging(int value);
    partial void OnIdEstructuraChanged();
    partial void OnCodNivelChanging(string value);
    partial void OnCodNivelChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnNivelChanging(System.Nullable<int> value);
    partial void OnNivelChanged();
    partial void OnidPadreChanging(System.Nullable<int> value);
    partial void OnidPadreChanged();
    partial void OnOrdenChanging(System.Nullable<int> value);
    partial void OnOrdenChanged();
    partial void OnCodCompletoChanging(string value);
    partial void OnCodCompletoChanged();
    #endregion
		
		public tRiesgos_Clasificaciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstructura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEstructura
		{
			get
			{
				return this._IdEstructura;
			}
			set
			{
				if ((this._IdEstructura != value))
				{
					this.OnIdEstructuraChanging(value);
					this.SendPropertyChanging();
					this._IdEstructura = value;
					this.SendPropertyChanged("IdEstructura");
					this.OnIdEstructuraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodNivel", DbType="NVarChar(10)")]
		public string CodNivel
		{
			get
			{
				return this._CodNivel;
			}
			set
			{
				if ((this._CodNivel != value))
				{
					this.OnCodNivelChanging(value);
					this.SendPropertyChanging();
					this._CodNivel = value;
					this.SendPropertyChanged("CodNivel");
					this.OnCodNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="Int")]
		public System.Nullable<int> Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this.OnNivelChanging(value);
					this.SendPropertyChanging();
					this._Nivel = value;
					this.SendPropertyChanged("Nivel");
					this.OnNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPadre", DbType="Int")]
		public System.Nullable<int> idPadre
		{
			get
			{
				return this._idPadre;
			}
			set
			{
				if ((this._idPadre != value))
				{
					this.OnidPadreChanging(value);
					this.SendPropertyChanging();
					this._idPadre = value;
					this.SendPropertyChanged("idPadre");
					this.OnidPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int")]
		public System.Nullable<int> Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCompleto", DbType="NVarChar(250)")]
		public string CodCompleto
		{
			get
			{
				return this._CodCompleto;
			}
			set
			{
				if ((this._CodCompleto != value))
				{
					this.OnCodCompletoChanging(value);
					this.SendPropertyChanging();
					this._CodCompleto = value;
					this.SendPropertyChanged("CodCompleto");
					this.OnCodCompletoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.qRiesgosNombres")]
	public partial class qRiesgosNombre
	{
		
		private int _IdRiesgo;
		
		private string _CodRiesgo;
		
		private string _CodRiesgoGenerico;
		
		private string _CodRiesgoLocalizado;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _Ejemplo;
		
		private string _Categoria;
		
		private string _Clasif1;
		
		private string _Clasif2;
		
		private string _Clasif3;
		
		private System.Nullable<int> _IdCategoria;
		
		private System.Nullable<int> _IdClasificacion1;
		
		private System.Nullable<int> _IdClasificacion2;
		
		private System.Nullable<int> _IdClasificacion3;
		
		private System.Nullable<int> _Nivel;
		
		private string _Justificacion;
		
		private System.Nullable<int> _IdSegmentacion1;
		
		private System.Nullable<int> _IdResponsable;
		
		private System.Nullable<int> _IdSupervisor;
		
		private System.Nullable<int> _IdControlesOportunidad;
		
		private System.Nullable<int> _IdControlesEfectividad;
		
		public qRiesgosNombre()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRiesgo", DbType="Int NOT NULL")]
		public int IdRiesgo
		{
			get
			{
				return this._IdRiesgo;
			}
			set
			{
				if ((this._IdRiesgo != value))
				{
					this._IdRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRiesgo", DbType="NVarChar(50)")]
		public string CodRiesgo
		{
			get
			{
				return this._CodRiesgo;
			}
			set
			{
				if ((this._CodRiesgo != value))
				{
					this._CodRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRiesgoGenerico", DbType="NVarChar(50)")]
		public string CodRiesgoGenerico
		{
			get
			{
				return this._CodRiesgoGenerico;
			}
			set
			{
				if ((this._CodRiesgoGenerico != value))
				{
					this._CodRiesgoGenerico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRiesgoLocalizado", DbType="NVarChar(250)")]
		public string CodRiesgoLocalizado
		{
			get
			{
				return this._CodRiesgoLocalizado;
			}
			set
			{
				if ((this._CodRiesgoLocalizado != value))
				{
					this._CodRiesgoLocalizado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ejemplo", DbType="NVarChar(250)")]
		public string Ejemplo
		{
			get
			{
				return this._Ejemplo;
			}
			set
			{
				if ((this._Ejemplo != value))
				{
					this._Ejemplo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NVarChar(50)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clasif1", DbType="NVarChar(250)")]
		public string Clasif1
		{
			get
			{
				return this._Clasif1;
			}
			set
			{
				if ((this._Clasif1 != value))
				{
					this._Clasif1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clasif2", DbType="NVarChar(250)")]
		public string Clasif2
		{
			get
			{
				return this._Clasif2;
			}
			set
			{
				if ((this._Clasif2 != value))
				{
					this._Clasif2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clasif3", DbType="NVarChar(250)")]
		public string Clasif3
		{
			get
			{
				return this._Clasif3;
			}
			set
			{
				if ((this._Clasif3 != value))
				{
					this._Clasif3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int")]
		public System.Nullable<int> IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClasificacion1", DbType="Int")]
		public System.Nullable<int> IdClasificacion1
		{
			get
			{
				return this._IdClasificacion1;
			}
			set
			{
				if ((this._IdClasificacion1 != value))
				{
					this._IdClasificacion1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClasificacion2", DbType="Int")]
		public System.Nullable<int> IdClasificacion2
		{
			get
			{
				return this._IdClasificacion2;
			}
			set
			{
				if ((this._IdClasificacion2 != value))
				{
					this._IdClasificacion2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClasificacion3", DbType="Int")]
		public System.Nullable<int> IdClasificacion3
		{
			get
			{
				return this._IdClasificacion3;
			}
			set
			{
				if ((this._IdClasificacion3 != value))
				{
					this._IdClasificacion3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="Int")]
		public System.Nullable<int> Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this._Nivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Justificacion", DbType="NVarChar(MAX)")]
		public string Justificacion
		{
			get
			{
				return this._Justificacion;
			}
			set
			{
				if ((this._Justificacion != value))
				{
					this._Justificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSegmentacion1", DbType="Int")]
		public System.Nullable<int> IdSegmentacion1
		{
			get
			{
				return this._IdSegmentacion1;
			}
			set
			{
				if ((this._IdSegmentacion1 != value))
				{
					this._IdSegmentacion1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResponsable", DbType="Int")]
		public System.Nullable<int> IdResponsable
		{
			get
			{
				return this._IdResponsable;
			}
			set
			{
				if ((this._IdResponsable != value))
				{
					this._IdResponsable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSupervisor", DbType="Int")]
		public System.Nullable<int> IdSupervisor
		{
			get
			{
				return this._IdSupervisor;
			}
			set
			{
				if ((this._IdSupervisor != value))
				{
					this._IdSupervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdControlesOportunidad", DbType="Int")]
		public System.Nullable<int> IdControlesOportunidad
		{
			get
			{
				return this._IdControlesOportunidad;
			}
			set
			{
				if ((this._IdControlesOportunidad != value))
				{
					this._IdControlesOportunidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdControlesEfectividad", DbType="Int")]
		public System.Nullable<int> IdControlesEfectividad
		{
			get
			{
				return this._IdControlesEfectividad;
			}
			set
			{
				if ((this._IdControlesEfectividad != value))
				{
					this._IdControlesEfectividad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tRiesgosEvaluaciones")]
	public partial class tRiesgosEvaluaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEvaluacion;
		
		private System.Nullable<int> _IdRiesgo;
		
		private System.Nullable<int> _IdNivel;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private bool _Activa;
		
		private bool _Ultima;
		
		private System.Nullable<int> _IdFrecAntes;
		
		private System.Nullable<int> _IdSeveAntes;
		
		private System.Nullable<int> _IdFrecDespues;
		
		private System.Nullable<int> _IdSeveDespues;
		
		private System.Nullable<int> _IdSevePeorAntes;
		
		private System.Nullable<int> _IdSevePeorDespues;
		
		private System.Nullable<int> _idEfectividad;
		
		private System.Nullable<double> _Efectividad;
		
		private System.Nullable<int> _IdFrecPlanDespues;
		
		private System.Nullable<int> _IdSevePlanDespues;
		
		private System.Nullable<int> _IdSevePeorPlanDespues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEvaluacionChanging(int value);
    partial void OnIdEvaluacionChanged();
    partial void OnIdRiesgoChanging(System.Nullable<int> value);
    partial void OnIdRiesgoChanged();
    partial void OnIdNivelChanging(System.Nullable<int> value);
    partial void OnIdNivelChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnActivaChanging(bool value);
    partial void OnActivaChanged();
    partial void OnUltimaChanging(bool value);
    partial void OnUltimaChanged();
    partial void OnIdFrecAntesChanging(System.Nullable<int> value);
    partial void OnIdFrecAntesChanged();
    partial void OnIdSeveAntesChanging(System.Nullable<int> value);
    partial void OnIdSeveAntesChanged();
    partial void OnIdFrecDespuesChanging(System.Nullable<int> value);
    partial void OnIdFrecDespuesChanged();
    partial void OnIdSeveDespuesChanging(System.Nullable<int> value);
    partial void OnIdSeveDespuesChanged();
    partial void OnIdSevePeorAntesChanging(System.Nullable<int> value);
    partial void OnIdSevePeorAntesChanged();
    partial void OnIdSevePeorDespuesChanging(System.Nullable<int> value);
    partial void OnIdSevePeorDespuesChanged();
    partial void OnidEfectividadChanging(System.Nullable<int> value);
    partial void OnidEfectividadChanged();
    partial void OnEfectividadChanging(System.Nullable<double> value);
    partial void OnEfectividadChanged();
    partial void OnIdFrecPlanDespuesChanging(System.Nullable<int> value);
    partial void OnIdFrecPlanDespuesChanged();
    partial void OnIdSevePlanDespuesChanging(System.Nullable<int> value);
    partial void OnIdSevePlanDespuesChanged();
    partial void OnIdSevePeorPlanDespuesChanging(System.Nullable<int> value);
    partial void OnIdSevePeorPlanDespuesChanged();
    #endregion
		
		public tRiesgosEvaluaciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEvaluacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEvaluacion
		{
			get
			{
				return this._IdEvaluacion;
			}
			set
			{
				if ((this._IdEvaluacion != value))
				{
					this.OnIdEvaluacionChanging(value);
					this.SendPropertyChanging();
					this._IdEvaluacion = value;
					this.SendPropertyChanged("IdEvaluacion");
					this.OnIdEvaluacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRiesgo", DbType="Int")]
		public System.Nullable<int> IdRiesgo
		{
			get
			{
				return this._IdRiesgo;
			}
			set
			{
				if ((this._IdRiesgo != value))
				{
					this.OnIdRiesgoChanging(value);
					this.SendPropertyChanging();
					this._IdRiesgo = value;
					this.SendPropertyChanged("IdRiesgo");
					this.OnIdRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNivel", DbType="Int")]
		public System.Nullable<int> IdNivel
		{
			get
			{
				return this._IdNivel;
			}
			set
			{
				if ((this._IdNivel != value))
				{
					this.OnIdNivelChanging(value);
					this.SendPropertyChanging();
					this._IdNivel = value;
					this.SendPropertyChanged("IdNivel");
					this.OnIdNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activa", DbType="Bit NOT NULL")]
		public bool Activa
		{
			get
			{
				return this._Activa;
			}
			set
			{
				if ((this._Activa != value))
				{
					this.OnActivaChanging(value);
					this.SendPropertyChanging();
					this._Activa = value;
					this.SendPropertyChanged("Activa");
					this.OnActivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ultima", DbType="Bit NOT NULL")]
		public bool Ultima
		{
			get
			{
				return this._Ultima;
			}
			set
			{
				if ((this._Ultima != value))
				{
					this.OnUltimaChanging(value);
					this.SendPropertyChanging();
					this._Ultima = value;
					this.SendPropertyChanged("Ultima");
					this.OnUltimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFrecAntes", DbType="Int")]
		public System.Nullable<int> IdFrecAntes
		{
			get
			{
				return this._IdFrecAntes;
			}
			set
			{
				if ((this._IdFrecAntes != value))
				{
					this.OnIdFrecAntesChanging(value);
					this.SendPropertyChanging();
					this._IdFrecAntes = value;
					this.SendPropertyChanged("IdFrecAntes");
					this.OnIdFrecAntesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSeveAntes", DbType="Int")]
		public System.Nullable<int> IdSeveAntes
		{
			get
			{
				return this._IdSeveAntes;
			}
			set
			{
				if ((this._IdSeveAntes != value))
				{
					this.OnIdSeveAntesChanging(value);
					this.SendPropertyChanging();
					this._IdSeveAntes = value;
					this.SendPropertyChanged("IdSeveAntes");
					this.OnIdSeveAntesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFrecDespues", DbType="Int")]
		public System.Nullable<int> IdFrecDespues
		{
			get
			{
				return this._IdFrecDespues;
			}
			set
			{
				if ((this._IdFrecDespues != value))
				{
					this.OnIdFrecDespuesChanging(value);
					this.SendPropertyChanging();
					this._IdFrecDespues = value;
					this.SendPropertyChanged("IdFrecDespues");
					this.OnIdFrecDespuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSeveDespues", DbType="Int")]
		public System.Nullable<int> IdSeveDespues
		{
			get
			{
				return this._IdSeveDespues;
			}
			set
			{
				if ((this._IdSeveDespues != value))
				{
					this.OnIdSeveDespuesChanging(value);
					this.SendPropertyChanging();
					this._IdSeveDespues = value;
					this.SendPropertyChanged("IdSeveDespues");
					this.OnIdSeveDespuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSevePeorAntes", DbType="Int")]
		public System.Nullable<int> IdSevePeorAntes
		{
			get
			{
				return this._IdSevePeorAntes;
			}
			set
			{
				if ((this._IdSevePeorAntes != value))
				{
					this.OnIdSevePeorAntesChanging(value);
					this.SendPropertyChanging();
					this._IdSevePeorAntes = value;
					this.SendPropertyChanged("IdSevePeorAntes");
					this.OnIdSevePeorAntesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSevePeorDespues", DbType="Int")]
		public System.Nullable<int> IdSevePeorDespues
		{
			get
			{
				return this._IdSevePeorDespues;
			}
			set
			{
				if ((this._IdSevePeorDespues != value))
				{
					this.OnIdSevePeorDespuesChanging(value);
					this.SendPropertyChanging();
					this._IdSevePeorDespues = value;
					this.SendPropertyChanged("IdSevePeorDespues");
					this.OnIdSevePeorDespuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEfectividad", DbType="Int")]
		public System.Nullable<int> idEfectividad
		{
			get
			{
				return this._idEfectividad;
			}
			set
			{
				if ((this._idEfectividad != value))
				{
					this.OnidEfectividadChanging(value);
					this.SendPropertyChanging();
					this._idEfectividad = value;
					this.SendPropertyChanged("idEfectividad");
					this.OnidEfectividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Efectividad", DbType="Float")]
		public System.Nullable<double> Efectividad
		{
			get
			{
				return this._Efectividad;
			}
			set
			{
				if ((this._Efectividad != value))
				{
					this.OnEfectividadChanging(value);
					this.SendPropertyChanging();
					this._Efectividad = value;
					this.SendPropertyChanged("Efectividad");
					this.OnEfectividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFrecPlanDespues", DbType="Int")]
		public System.Nullable<int> IdFrecPlanDespues
		{
			get
			{
				return this._IdFrecPlanDespues;
			}
			set
			{
				if ((this._IdFrecPlanDespues != value))
				{
					this.OnIdFrecPlanDespuesChanging(value);
					this.SendPropertyChanging();
					this._IdFrecPlanDespues = value;
					this.SendPropertyChanged("IdFrecPlanDespues");
					this.OnIdFrecPlanDespuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSevePlanDespues", DbType="Int")]
		public System.Nullable<int> IdSevePlanDespues
		{
			get
			{
				return this._IdSevePlanDespues;
			}
			set
			{
				if ((this._IdSevePlanDespues != value))
				{
					this.OnIdSevePlanDespuesChanging(value);
					this.SendPropertyChanging();
					this._IdSevePlanDespues = value;
					this.SendPropertyChanged("IdSevePlanDespues");
					this.OnIdSevePlanDespuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSevePeorPlanDespues", DbType="Int")]
		public System.Nullable<int> IdSevePeorPlanDespues
		{
			get
			{
				return this._IdSevePeorPlanDespues;
			}
			set
			{
				if ((this._IdSevePeorPlanDespues != value))
				{
					this.OnIdSevePeorPlanDespuesChanging(value);
					this.SendPropertyChanging();
					this._IdSevePeorPlanDespues = value;
					this.SendPropertyChanged("IdSevePeorPlanDespues");
					this.OnIdSevePeorPlanDespuesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tEva_Frecuencia")]
	public partial class tEva_Frecuencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEvaFrecuencia;
		
		private string _Frecuencia;
		
		private string _Descrip;
		
		private string _Riesgo;
		
		private System.Nullable<double> _Matriz;
		
		private System.Nullable<double> _FrecMedia;
		
		private System.Nullable<int> _Orden;
		
		private string _Color;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEvaFrecuenciaChanging(int value);
    partial void OnIdEvaFrecuenciaChanged();
    partial void OnFrecuenciaChanging(string value);
    partial void OnFrecuenciaChanged();
    partial void OnDescripChanging(string value);
    partial void OnDescripChanged();
    partial void OnRiesgoChanging(string value);
    partial void OnRiesgoChanged();
    partial void OnMatrizChanging(System.Nullable<double> value);
    partial void OnMatrizChanged();
    partial void OnFrecMediaChanging(System.Nullable<double> value);
    partial void OnFrecMediaChanged();
    partial void OnOrdenChanging(System.Nullable<int> value);
    partial void OnOrdenChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    #endregion
		
		public tEva_Frecuencia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEvaFrecuencia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEvaFrecuencia
		{
			get
			{
				return this._IdEvaFrecuencia;
			}
			set
			{
				if ((this._IdEvaFrecuencia != value))
				{
					this.OnIdEvaFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._IdEvaFrecuencia = value;
					this.SendPropertyChanged("IdEvaFrecuencia");
					this.OnIdEvaFrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="NVarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this.OnFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._Frecuencia = value;
					this.SendPropertyChanged("Frecuencia");
					this.OnFrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrip", DbType="NVarChar(250)")]
		public string Descrip
		{
			get
			{
				return this._Descrip;
			}
			set
			{
				if ((this._Descrip != value))
				{
					this.OnDescripChanging(value);
					this.SendPropertyChanging();
					this._Descrip = value;
					this.SendPropertyChanged("Descrip");
					this.OnDescripChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Riesgo", DbType="NVarChar(250)")]
		public string Riesgo
		{
			get
			{
				return this._Riesgo;
			}
			set
			{
				if ((this._Riesgo != value))
				{
					this.OnRiesgoChanging(value);
					this.SendPropertyChanging();
					this._Riesgo = value;
					this.SendPropertyChanged("Riesgo");
					this.OnRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matriz", DbType="Float")]
		public System.Nullable<double> Matriz
		{
			get
			{
				return this._Matriz;
			}
			set
			{
				if ((this._Matriz != value))
				{
					this.OnMatrizChanging(value);
					this.SendPropertyChanging();
					this._Matriz = value;
					this.SendPropertyChanged("Matriz");
					this.OnMatrizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrecMedia", DbType="Float")]
		public System.Nullable<double> FrecMedia
		{
			get
			{
				return this._FrecMedia;
			}
			set
			{
				if ((this._FrecMedia != value))
				{
					this.OnFrecMediaChanging(value);
					this.SendPropertyChanging();
					this._FrecMedia = value;
					this.SendPropertyChanged("FrecMedia");
					this.OnFrecMediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int")]
		public System.Nullable<int> Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tEva_Severidad")]
	public partial class tEva_Severidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEvaSeveridad;
		
		private string _Severidad;
		
		private string _Impacto;
		
		private System.Nullable<double> _Matriz;
		
		private System.Nullable<double> _Media;
		
		private System.Nullable<double> _LimSuperior;
		
		private System.Nullable<double> _Matriz2;
		
		private System.Nullable<int> _Orden;
		
		private string _Color;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEvaSeveridadChanging(int value);
    partial void OnIdEvaSeveridadChanged();
    partial void OnSeveridadChanging(string value);
    partial void OnSeveridadChanged();
    partial void OnImpactoChanging(string value);
    partial void OnImpactoChanged();
    partial void OnMatrizChanging(System.Nullable<double> value);
    partial void OnMatrizChanged();
    partial void OnMediaChanging(System.Nullable<double> value);
    partial void OnMediaChanged();
    partial void OnLimSuperiorChanging(System.Nullable<double> value);
    partial void OnLimSuperiorChanged();
    partial void OnMatriz2Changing(System.Nullable<double> value);
    partial void OnMatriz2Changed();
    partial void OnOrdenChanging(System.Nullable<int> value);
    partial void OnOrdenChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    #endregion
		
		public tEva_Severidad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEvaSeveridad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEvaSeveridad
		{
			get
			{
				return this._IdEvaSeveridad;
			}
			set
			{
				if ((this._IdEvaSeveridad != value))
				{
					this.OnIdEvaSeveridadChanging(value);
					this.SendPropertyChanging();
					this._IdEvaSeveridad = value;
					this.SendPropertyChanged("IdEvaSeveridad");
					this.OnIdEvaSeveridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Severidad", DbType="NVarChar(50)")]
		public string Severidad
		{
			get
			{
				return this._Severidad;
			}
			set
			{
				if ((this._Severidad != value))
				{
					this.OnSeveridadChanging(value);
					this.SendPropertyChanging();
					this._Severidad = value;
					this.SendPropertyChanged("Severidad");
					this.OnSeveridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impacto", DbType="NVarChar(250)")]
		public string Impacto
		{
			get
			{
				return this._Impacto;
			}
			set
			{
				if ((this._Impacto != value))
				{
					this.OnImpactoChanging(value);
					this.SendPropertyChanging();
					this._Impacto = value;
					this.SendPropertyChanged("Impacto");
					this.OnImpactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matriz", DbType="Float")]
		public System.Nullable<double> Matriz
		{
			get
			{
				return this._Matriz;
			}
			set
			{
				if ((this._Matriz != value))
				{
					this.OnMatrizChanging(value);
					this.SendPropertyChanging();
					this._Matriz = value;
					this.SendPropertyChanged("Matriz");
					this.OnMatrizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Media", DbType="Float")]
		public System.Nullable<double> Media
		{
			get
			{
				return this._Media;
			}
			set
			{
				if ((this._Media != value))
				{
					this.OnMediaChanging(value);
					this.SendPropertyChanging();
					this._Media = value;
					this.SendPropertyChanged("Media");
					this.OnMediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimSuperior", DbType="Float")]
		public System.Nullable<double> LimSuperior
		{
			get
			{
				return this._LimSuperior;
			}
			set
			{
				if ((this._LimSuperior != value))
				{
					this.OnLimSuperiorChanging(value);
					this.SendPropertyChanging();
					this._LimSuperior = value;
					this.SendPropertyChanged("LimSuperior");
					this.OnLimSuperiorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matriz2", DbType="Float")]
		public System.Nullable<double> Matriz2
		{
			get
			{
				return this._Matriz2;
			}
			set
			{
				if ((this._Matriz2 != value))
				{
					this.OnMatriz2Changing(value);
					this.SendPropertyChanging();
					this._Matriz2 = value;
					this.SendPropertyChanged("Matriz2");
					this.OnMatriz2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int")]
		public System.Nullable<int> Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
