<?xml version="1.0" encoding="utf-8"?><Database Name="Risk" Class="Riesgos_BDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql.aulariosoft.com;Initial Catalog=RiskMVC;User ID=AuRisk" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RiskMVCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tRiesgos_Clasificaciones" Member="tRiesgos_Clasificaciones">
    <Type Name="tRiesgos_Clasificaciones">
      <Column Name="IdEstructura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodNivel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodCompleto" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgosEvaluaciones" Member="tRiesgosEvaluaciones">
    <Type Name="tRiesgosEvaluaciones">
      <Column Name="IdEvaluacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdRiesgo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Activa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ultima" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdFrecAntes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSeveAntes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdFrecDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSeveDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSevePeorAntes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSevePeorDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEfectividad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Efectividad" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IdFrecPlanDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSevePlanDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSevePeorPlanDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tEva_Frecuencia" Member="tEva_Frecuencia">
    <Type Name="tEva_Frecuencia">
      <Column Name="IdEvaFrecuencia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Frecuencia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Descrip" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Riesgo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Matriz" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FrecMedia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tEva_Severidad" Member="tEva_Severidad">
    <Type Name="tEva_Severidad">
      <Column Name="IdEvaSeveridad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Severidad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Impacto" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Matriz" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Media" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LimSuperior" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Matriz2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[qRiesgos_Evaluaciones _Valores]" Member="qRiesgos_Evaluaciones_Valores">
    <Type Name="qRiesgos_Evaluaciones_Valores">
      <Column Name="IdRiesgo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ultima" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdFrecAntes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreFrecAntes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorFrecAntes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdFrecDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreFrecDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorFrecDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdFrecPlanDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreFrecPlanDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorFrecPlanDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdSeveAntes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSeveAntes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorSeveAntes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdSeveDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSeveDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorSeveDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdSevePlanDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSevePlanDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorSevePlanDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdSevePeorAntes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSevePeorAntes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorSevePeorAntes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdSevePeorDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSevePeorDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorSevePeorDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdSevePeorPlanDespues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSevePeorPlanDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColorSevePeorPlanDespues" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos" Member="tRiesgos">
    <Type Name="tRiesgos">
      <Column Name="IdRiesgo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodRiesgoGenerico" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodRiesgo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodRiesgoLocalizado" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdClasificacion1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdClasificacion2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdClasificacion3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ejemplo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Justificacion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IdSegmentacion1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdResponsable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdControlesOportunidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdControlesEfectividad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vigencia" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_Categorias" Member="tRiesgos_Categorias">
    <Type Name="tRiesgos_Categorias">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.qRiesgosNombres" Member="qRiesgosNombres">
    <Type Name="qRiesgosNombres">
      <Column Name="IdRiesgo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodRiesgo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodRiesgoGenerico" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodRiesgoLocalizado" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ejemplo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Clasif1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Clasif2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Clasif3" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdClasificacion1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdClasificacion2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdClasificacion3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Justificacion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IdSegmentacion1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdResponsable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdControlesOportunidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Oportunidad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdControlesEfectividad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Efectividad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_ControlOportunidad" Member="tRiesgos_ControlOportunidad">
    <Type Name="tRiesgos_ControlOportunidad">
      <Column Name="IdControlOportunidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Oportunidad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_ControlEfectividad" Member="tRiesgos_ControlEfectividad">
    <Type Name="tRiesgos_ControlEfectividad">
      <Column Name="IdControlEfectividad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Efectividad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tResponsables" Member="tResponsables">
    <Type Name="tResponsables">
      <Column Name="IdResponsable" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telefono2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRiesgos_Segmentacion1" Member="tRiesgos_Segmentacion1">
    <Type Name="tRiesgos_Segmentacion1">
      <Column Name="IdSegmenta1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Segmentacion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tEstructura" Member="tEstructura">
    <Type Name="tEstructura">
      <Column Name="IdEstructura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodNivel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Responsable" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Nivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodCompleto" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.qEstructura_Contenidos_Def" Member="qEstructura_Contenidos_Def">
    <Type Name="qEstructura_Contenidos_Def">
      <Column Name="IdEstructura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contenido" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tRelEstructuraRiesgos" Member="tRelEstructuraRiesgos">
    <Type Name="tRelEstructuraRiesgos">
      <Column Name="IdEstruturaRiesgo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdEstructura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdRiesgo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>